- name: Install curl and gnupg
  ansible.builtin.apt:
    name: [curl, gnupg]
    state: present
    update_cache: yes

- name: Add Node.js 18.x APT key
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Install PM2 globally
  community.general.npm:
    name: pm2
    global: yes

- name: Create frontend app directory
  ansible.builtin.file:
    path: /var/www/frontend
    state: directory
    mode: "0755"

- name: Copy frontend files from control node
  ansible.builtin.copy:
    src: /home/azureuser/3-tier-app-automation/frontend/
    dest: /var/www/frontend/
    owner: www-data
    group: www-data
    mode: "0755"

- name: Copy environment variables file
  ansible.builtin.template:
    src: env.j2
    dest: /var/www/frontend/.env
    mode: "0644"

- name: Install npm dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /var/www/frontend
    creates: /var/www/frontend/node_modules

- name: Build frontend app
  ansible.builtin.command: npm run build
  args:
    chdir: /var/www/frontend

- name: Start frontend app with PM2
  ansible.builtin.shell: |
    pm2 start {{ frontend_start_command }} --name "{{ frontend_pm2_process_name }}"
    pm2 save
    pm2 startup systemd -u {{ ansible_user }} --hp /home/{{ ansible_user }}
