- name: Install Node.js & npm
  apt:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: ["docker.io"]
    state: present
    update_cache: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: azureuser
    groups: docker
    append: yes

- name: Clone frontend app from repo
  git:
    repo: "{{ frontend_repo_url }}"
    dest: /home/azureuser/frontend

- name: Install frontend dependencies
  npm:
    path: /home/azureuser/frontend

- name: Start frontend app
  shell: nohup npm start &
  args:
    chdir: /home/azureuser/frontend

