prefix               = "DevOps1-week9-shadaAlharbi-prod"
location             = "UAE North"
vm_size              = "Standard_D2s_v3"
admin_username       = "azureuser"
admin_password       = "SuperSecurePassword!"
sql_admin_username   = "sqladmin"
sql_admin_password   = "SuperSecurePassword!"
db_sku               = "Standard"
