- name: Check if Docker is already installed
  command: which docker
  register: docker_check
  ignore_errors: true

- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
    update_cache: yes
  when: docker_check.rc != 0

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_check.rc != 0

- name: Add Docker APT repository for correct Ubuntu version
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
  when: docker_check.rc != 0

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  when: docker_check.rc != 0

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Confirm Docker is installed correctly
  command: docker --version
  register: docker_version_check
  failed_when: docker_version_check.rc != 0

  - name: Force reboot after Docker install to ensure group permissions take effect
  reboot:
    msg: "Rebooting after Docker installation"
    pre_reboot_delay: 5
    post_reboot_delay: 10
  when: docker_check.rc != 0

