# - name: Check if Docker is already installed
#   command: which docker
#   register: docker_check
#   ignore_errors: yes

# - name: Install required packages
#   apt:
#     name:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - software-properties-common
#     state: present
#     update_cache: yes
#   when: docker_check.rc != 0

# - name: Add Docker GPG key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present
#   when: docker_check.rc != 0

# - name: Add Docker repository
#   apt_repository:
#     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#     state: present
#   when: docker_check.rc != 0

# - name: Install Docker CE
#   apt:
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#     state: latest
#     update_cache: yes
#   when: docker_check.rc != 0

# - name: Ensure Docker service is running
#   systemd:
#     name: docker
#     enabled: true
#     state: started

# - name: Add user to docker group
#   user:
#     name: "{{ ansible_user }}"
#     groups: docker
#     append: yes

# - name: Reboot if user was added to docker group
#   reboot:
#   when: docker_check.rc != 0


- name: Install Docker on remote servers and configure non-sudo access
 hosts: all
 become: true
 vars:
   docker_release: "{{ ansible_distribution_release | lower }}"  # e.g., jammy for Ubuntu 22.04
 tasks:
   - name: Update the apt cache
     ansible.builtin.apt:
       update_cache: yes
       cache_valid_time: 3600

   - name: Create apt keyrings directory if it doesn't exist
     ansible.builtin.file:
       path: /etc/apt/keyrings
       state: directory
       mode: "0755"

   - name: Add Docker's official GPG key into the keyring
     ansible.builtin.apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
       keyring: /etc/apt/keyrings/docker.gpg

   - name: Add Docker apt repository with signed-by option
     ansible.builtin.apt_repository:
       repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ docker_release }} stable"
       state: present
       filename: docker

   - name: Update apt cache after adding Docker repository
     ansible.builtin.apt:
       update_cache: yes

   - name: Install Docker CE, Docker CLI, and containerd.io
     ansible.builtin.apt:
       name:
         - docker-ce
         - docker-ce-cli
         - containerd.io
       state: present

   - name: Ensure Docker service is started and enabled
     ansible.builtin.service:
       name: docker
       state: started
       enabled: yes

   - name: Add user to docker group for non-sudo Docker commands
     ansible.builtin.user:
       name: "{{ ansible_user }}"
       groups: docker
       append: yes