- name: Create app directory
  file:
    path: "{{ app_dest_dir }}"
    state: directory
    mode: '0755'

- name: Copy app files to remote
  copy:
    src: "{{ app_src_dir }}/"
    dest: "{{ app_dest_dir }}/"
    mode: '0644'

- name: Build Docker image
  community.docker.docker_image:
    name: "{{ app_image }}"
    build:
      path: "{{ app_dest_dir }}"
    source: build
  notify: restart app container

- name: Run Docker container
  community.docker.docker_container:
    name: "{{ app_container }}"
    image: "{{ app_image }}"
    restart_policy: always
    state: started
    ports:
      - "{{ exposed_port }}:{{ container_port }}"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      DB_CONNECTION_STRING: "{{ db_connection_string | default('') }}"
