- name: Pull SonarQube image
  community.docker.docker_image:
    name: sonarqube
    tag: lts
    source: pull

- name: Run SonarQube container
  community.docker.docker_container:
    name: sonarqube
    image: sonarqube:lts
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    env:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
