---
# ✅ 1. أول شيء: تأكد Docker مثبت على جميع الـVMs
- hosts: all
  become: true
  roles:
    - role: docker_installation

# ✅ 2. الآن نشغّل SonarQube فقط بعد ما تأكدنا Docker جاهز عليه
- hosts: sonarqube
  become: true
  roles:
    - role: sonarqube

# ✅ 3. الآن ننظف الشبكة والحاويات على كل VM
- hosts: all
  become: true
  roles:
    - role: cleanup
      vars:
        docker_containers: [ frontend, backend ]
        docker_images: [ frontend, backend ]
        folders_to_delete: [ /tmp/frontend, /tmp/backend ]
        docker_network_name: app_net

# ✅ 4. ننشئ شبكة Docker جديدة
- hosts: all
  become: true
  roles:
    - role: docker_network
      vars:
        docker_network_name: app_net

# ✅ 5. ننشر تطبيق الفرونت على كل الـfrontend VMs
- hosts: frontend
  become: true
  roles:
    - role: application
      vars:
        app_name: frontend
        app_image: frontend
        app_container: frontend
        app_src_dir: ../frontend
        app_dest_dir: /tmp/frontend
        exposed_port: 80
        container_port: 3000
        docker_network_name: app_net
        db_connection_string: ""

# ✅ 6. ننشر تطبيق الباك على كل الـbackend VMs
- hosts: backend
  become: true
  roles:
    - role: application
      vars:
        app_name: backend
        app_image: backend
        app_container: backend
        app_src_dir: ../backend
        app_dest_dir: /tmp/backend
        exposed_port: 3000
        container_port: 3000
        docker_network_name: app_net
        db_connection_string: "Server=<SQL_SERVER>;Database=<DB_NAME>;User Id=<USER>;Password=<PASSWORD>;"
