---
- hosts: all
  become: true
  roles:
    - docker_installation

- hosts: sonarqube
  become: true
  roles:
    - sonarqube

- hosts: all
  become: true
  roles:
    - cleanup
      vars:
        docker_containers: [frontend, backend]
        docker_images: [frontend, backend]
        folders_to_delete: [ /tmp/frontend, /tmp/backend ]
        docker_network_name: app_net

- hosts: all
  become: true
  roles:
    - docker_network
      vars:
        docker_network_name: app_net

- hosts: frontend
  become: true
  roles:
    - application
      vars:
        app_name: frontend
        app_image: frontend
        app_container: frontend
        app_src_dir: ../frontend
        app_dest_dir: /tmp/frontend
        exposed_port: 80
        container_port: 3000
        docker_network_name: app_net
        db_connection_string: ""

- hosts: backend
  become: true
  roles:
    - application
      vars:
        app_name: backend
        app_image: backend
        app_container: backend
        app_src_dir: ../backend
        app_dest_dir: /tmp/backend
        exposed_port: 3000
        container_port: 3000
        docker_network_name: app_net
        db_connection_string: "Server=<SQL_SERVER>;Database=<DB_NAME>;User Id=<USER>;Password=<PASSWORD>;"
