---
- name: Install Docker on Azure VMs
  hosts: all
  become: true
  roles:
    - docker_install

- name: Configure Backend VMs
  hosts: backend
  become: yes
  roles:
    - backend

- name: Configure Frontend VMs
  hosts: frontend
  become: yes
  roles:
    - frontend

- name: Setup SonarQube
  hosts: sonarqube
  become: yes
  roles:
    - sonarqube
