- name: Configure 3-tier application
  hosts: all
  become: yes
  roles:
    - { role: frontend, when: "'frontend' in group_names" }
    - { role: backend, when: "'backend' in group_names" }
    - { role: sonarqube, when: "'sonarqube' in group_names" }

